### ISSUE TITLE
杭州 - 九月 Node Party 微话题征集

### ISSUE THREAD

**Issue by xudafeng** [cnodejs/nodeparty#18]
[九月 Node Party 活动介绍](https://cnodejs.org/topic/5b911f1837b3005a0b0e6c16)

微话题尽量在 5 min 内讲清楚核心内容。

报名格式：

- 话题名称
- 内容简介

**Comment by fengmk2** [comment]
报名：给大家晒晒 npm.taobao.org 一年要花掉多少钱。

如果到时候时间合适，希望能到现场分享一下花阿里云的钱有多少爽。
