### ISSUE TITLE
12月21号，NodeParty杭州站

### ISSUE THREAD

**Issue by JacksonTian** [cnodejs/nodeparty#2]
阔别一年的NodeParty再度开启。

阿里巴巴西溪园区1-2-17 白马山庄 [地图](http://j.map.baidu.com/tM3S6)

报名参与方式：按{GitHub id, 是否开车前来（针对非阿里员工）}格式回复issue即可。

参会人数：100

费用：免费

时间安排：
1:30 签到
2:00 正式开始
5:00 结束

主要议题：
- @dead-horse: 《cnpmjs.org》，国产npm的逆袭. [Slides](http://deadhorse.me/slides/cnpmjs.html) |  [现场代码视频](http://v.youku.com/v_show/id_XNjUxNzI2MDg4.html)
- @lifesinger: 《面向无线的前端架构》无线时代，Node 在前端领域的尝试。[Slides](http://nfs.nodeblog.org/d/9/d92a66c63f900f0870333aefc2c65e07.pdf)
- Node Job
- @q3boy 《honeycomb简介》——用nodejs实现的web server容器
- @JacksonTian: 《简谈“深浅”》[Slides](http://nfs.nodeblog.org/9/7/97d7261c097ecf73f5b5aba7fbdcdf92.pdf)

礼品：
- 新书《深入浅出Node.js》
- 京JS T恤

**Comment by coolme200** [comment]
coolme200

**Comment by melotlee** [comment]
superlee.走路过去,

**Comment by wudi0431** [comment]
上海能参加么

**Comment by mjgaga** [comment]
mjgaga

**Comment by lonfee88** [comment]
lonfee88

**Comment by huxiangtao** [comment]
huxt

**Comment by JacksonTian** [comment]
@wudi0431 欢迎长三角地区的同学参加。

**Comment by psw1254** [comment]
psw1254

**Comment by weakish** [comment]
我想参加，但是不会NodeJS怎么破……

``` coffee
id : 'weakish', car : no
```

**Comment by xyhp915** [comment]
xyhp915  否

**Comment by OliverChanYes** [comment]
ifany

**Comment by tiye** [comment]
``` js
{id: "jiyinyiyong", car: false}
```

**Comment by fengmk2** [comment]
``` js
console.log('github: %s, car: "哈哈, 有车位了"', "fengmk2");
```

**Comment by dead-horse** [comment]
+1

**Comment by oluul** [comment]
{id:oluul,car:false}
帝都的过去参加不会介意吧？

**Comment by fengmk2** [comment]
@oluul 不介意, 欢迎来新雾都

**Comment by Bonkebo** [comment]
{Bonkebo , 否}

**Comment by wudi0431** [comment]
{id: "wudi0431", car: false}

**Comment by ye-ys** [comment]
想去啊，可是cnode社区为何不能注册＝ ＝留github ID行么  
piaoxu93  不开车

**Comment by jerryge** [comment]
{id:"jerryge",car:0}

**Comment by fakefish** [comment]
fakefish By 公交 @weakish 一起~

**Comment by Bonkebo** [comment]
新人，学生  问个问题 要交多少钱？

**Comment by JacksonTian** [comment]
@Bonkebo It's free.

**Comment by oluul** [comment]
@fengmk2 好，到时候好好欣赏贵都的雾景

**Comment by Bonkebo** [comment]
@JacksonTian  Thanks！

**Comment by wudi0431** [comment]
{wudi0431,否}

**Comment by tonyc726** [comment]
```
{"id": "tonyc620", "car": false}
```

**Comment by feiwen8772** [comment]
{"id": "feiwen8772", "car": false}

**Comment by ylnb91** [comment]
{"id": "ylnb91", "car": false}

**Comment by unrealinux** [comment]
unrealinux 没车可开

**Comment by ccforward** [comment]
{id: "ccforward", car: false}

**Comment by hutaoer** [comment]
good party!

**Comment by ykan** [comment]
{"id":"ykan"}

**Comment by chen-zeyu** [comment]
{"id“:”chen-zeyu“}

**Comment by liuyunclouder** [comment]
{id: "liuyunclouder", car: false}

**Comment by unrealinux** [comment]
怎么确认自己报名成功呢？时间更改了吗？

**Comment by JacksonTian** [comment]
@unrealinux 最后会有提醒的。

**Comment by ye-ys** [comment]
{piaoxu93, 不开车}

**Comment by mailzwj** [comment]
{id: "mailzwj", car: false}

**Comment by RobinQu** [comment]
{id: "RobinQu", car: true}

**Comment by magicx** [comment]
{magicx, 否}

**Comment by zerone7** [comment]
{id:”zerone7“, false}

**Comment by lichangwei** [comment]
{id: "lichangwei"}

**Comment by younglaker** [comment]
{"id": "younglaker", "car": false}

**Comment by fengmk2** [comment]
@dead_horse 主题是cnpm么？

**Comment by baokunguo** [comment]
{"id": "baokunguo", "car": false}

**Comment by dead-horse** [comment]
@fengmk2  是的

**Comment by JacksonTian** [comment]
@dead-horse 给下完整的名字，我更新issue

**Comment by dead-horse** [comment]
@JacksonTian 晚点，还没想好

**Comment by JacksonTian** [comment]
@dead-horse 请今天给出

**Comment by fengmk2** [comment]
期待啊！
在 2013-12-15 PM2:45，"dead_horse" notifications@github.com写道：

**Comment by jone369** [comment]
{"id":"jone369","car":false}，想了解nodejs，能去吗？

**Comment by moldauder** [comment]
{id: 'moldauder', car:false}

**Comment by lujiabz** [comment]
{"id":"gitoneman","car":"no"}

**Comment by xuemengfei** [comment]
``` javascript
{id: "xuemengfei", car: false}
```

**Comment by luckydrq** [comment]
{id: 'luckydrq', car: true}

**Comment by hellolibo** [comment]
{id: 'hellolibo', car:false}

**Comment by fengsage** [comment]
{id:'fengsage',car:false}

**Comment by woderia** [comment]
{"id": "woderia", "car": false}

**Comment by Neil-UWA** [comment]
{id: 'Neil-UWA', car: false}

**Comment by hidoos** [comment]
``` js
{"id": 'hidoos', "car": false}
```

**Comment by we11adam** [comment]
id: adamme
不开车

**Comment by JacksonTian** [comment]
感兴趣的都可以来。

在 2013年12月16日，下午12:20，jone369 notifications@github.com 写道：

**Comment by 4simple** [comment]
```
{id: '4simple', car: false}
```

**Comment by daxingplay** [comment]
``` json
{"id": "daxingplay", "car": true}
```

**Comment by X-Bird** [comment]
```
{"id": "x-bird", "car": false}
```

**Comment by lwbjing** [comment]
<pre>
{
    "id": "lwbjing",
    "car": false
}
</pre>

**Comment by purejs** [comment]
{"id": purejs, "car": false}

**Comment by crazyleaves** [comment]
{
    "id": "crazyleaves"
}

**Comment by xiaoman123** [comment]
{"id":"xiaoman123", "car":false}

**Comment by Jarvis-Q** [comment]
{"id": ''Jarvis-Q", "car": false}

**Comment by etkarl** [comment]
{"id": ''etkarl", "car": false}

**Comment by rubyisapm** [comment]
{"id":"skysunshine99","car":false}

**Comment by Wuvnen** [comment]
是员工，西溪没车位。

``` js
{id : 'Ysudo', car : true}
```

**Comment by akecn** [comment]
{"id":"akecn","car":false}

**Comment by dead-horse** [comment]
@JacksonTian  《`cnpmjs.org` ，国产npm的逆袭》 如何

**Comment by fengmk2** [comment]
@dead-horse 碉堡了

**Comment by baishuiz** [comment]
遥祝所有周六活动。

**Comment by waltzintherain** [comment]
{id: "waltzintherain", car: false}

**Comment by jixiangac** [comment]
{id:"jixiangac", car: false}

**Comment by alsotang** [comment]
{id: alsotang}

**Comment by ericdum** [comment]
{id: "[ericdum](https://github.com/ericdum/mujiang.info/issues?state=open)", car: true}

**Comment by xudafeng** [comment]
{id: "xudafeng", car:false}

**Comment by runkingzhang** [comment]
{id: "runkingzhang", car:false}

**Comment by gudh** [comment]
{id: "[siloyiwa](https://github.com/siloyiwa)", car: false}

**Comment by hujin** [comment]
{id:'hujin', car:false}

**Comment by pop2008** [comment]
{id: "pop2008", car: true}

**Comment by wenlong555** [comment]
+1  {id:wenlong555,car:true}

**Comment by qiushilee** [comment]
{ id: "qiushilee", car: true }

**Comment by noodlesC** [comment]
{id:"yuyuyuhang",car:false]

**Comment by robustfengbin** [comment]
{id:"robustfengbin",car:true]

**Comment by im-Dowe** [comment]
{ id: "im-dowe" ,car: false }

**Comment by q3058098** [comment]
{id : "q3058098", car : false}

**Comment by adohe-zz** [comment]
NodeParty上海站会有么....

**Comment by q3058098** [comment]
{id : 'q3058098', car : false}

**Comment by linkgod** [comment]
{"id": "linkgod", "car": false}

**Comment by Birdbird** [comment]
{'id':Birdbird, 'car': False}

**Comment by ishenli** [comment]
{
    "id": "ishenli",
    "car": false
}

**Comment by Birdbird** [comment]
{'id': 'chuck911', 'car': False}

**Comment by moqiqi** [comment]
{'id':"moqiqi", 'car': False}

**Comment by TreeLin** [comment]
{id: 'tree', car:false , company:'segmentfault'}

**Comment by JacksonTian** [comment]
明天的参会人员：

@coolme200,@melotlee,@wudi0431,@mjgaga,@lonfee88,@huxiangtao,@JacksonTian,@psw1254,@weakish,@xyhp915,@ifany,@jiyinyiyong,@fengmk2,@dead-horse,@oluul,@Bonkebo,@piaoxu93,@jerryge,@fakefish,@tonyc620,@feiwen8772,@ylnb91,@unrealinux,@ccforward,@hutaoer,@ykan,@chen-zeyu,@liuyunclouder,@mailzwj,@RobinQu,@magicx,@zerone7,@lichangwei,@younglaker,@baokunguo,@jone369,@moldauder,@gitoneman,@xuemengfei,@luckydrq,@hellolibo,@fengsage,@woderia,@Neil-UWA,@hidoos,@adamme,@leoshawn,@4simple,@daxingplay,@X-Bird,@lwbjing,@purejs,@crazyleaves,@xiaoman123,@Jarvis-Q,@etkarl,@skysunshine99,@Ysudo,@akecn,@baishuiz,@waltzintherain,@jixiangac,@alsotang,@ericdum,@xudafeng,@runkingzhang,@siloyiwa,@hujin,@pop2008,@wenlong555,@qiushilee,@yuyuyuhang,@robustfengbin,@im-Dowe,@q3058098,@AdoHe,@linkgod,@Birdbird,@ishenli,@moqiqi,@TreeLin 请各位从西溪北门（理工大对面）进入西溪园区

**Comment by JacksonTian** [comment]
@lwbjing,@purejs,@crazyleaves,@xiaoman123,@Jarvis-Q,@etkarl,@skysunshine99,@Ysudo,@akecn,@baishuiz,@waltzintherain,@jixiangac,@alsotang,@ericdum,@xudafeng,@runkingzhang,@siloyiwa,@hujin,@pop2008,@wenlong555,@qiushilee,@yuyuyuhang,@robustfengbin,@im-Dowe,@q3058098,@AdoHe,@linkgod,@Birdbird,@ishenli,@moqiqi,@TreeLin 请各位从西溪北门（理工大对面）进入西溪园区

**Comment by dai1768** [comment]
{id: "dai1768", car: false}

**Comment by leoner** [comment]
{id: "leoner", car: false}

**Comment by sjmjack** [comment]
{GitHub sjmjack, car: false}

**Comment by 06wj** [comment]
{id:06wj,car:null}

**Comment by xiongsongsong** [comment]
{id:xiongsongsong,car:false}

**Comment by sjmjack** [comment]
{id: "sjmjack", car: false}

**Comment by alankell** [comment]
id：”alankell ”  car：“false”

**Comment by discoverfly** [comment]
{id:“discoverfly", car: false}

**Comment by we11adam** [comment]
@JacksonTian 电脑进了豆浆…下午修电脑去，来不了了>.< 抱歉抱歉…

**Comment by RobinQu** [comment]
在门口，车不让进么？

发自我的 iPhone

**Comment by leoner** [comment]
会议室好像被人占了？

**Comment by suziewong** [comment]
{id:“suziewong",}

**Comment by fengmk2** [comment]
会议室临时调到  阿里巴巴西溪园区一号楼 1-2-17 白马山庄

**Comment by tiye** [comment]
求 PPT 链接 :)

**Comment by fengmk2** [comment]
目前已经收到的Slides 和视频
- @dead-horse: 《cnpmjs.org》，国产npm的逆袭. [Slides](http://deadhorse.me/slides/cnpmjs.html) |  [现场代码视频](http://v.youku.com/v_show/id_XNjUxNzI2MDg4.html)
- @lifesinger: 《面向无线的前端架构》无线时代，Node 在前端领域的尝试。[Slides](http://nfs.nodeblog.org/d/9/d92a66c63f900f0870333aefc2c65e07.pdf)
- @JacksonTian: 《简谈“深浅”》[Slides](http://nfs.nodeblog.org/9/7/97d7261c097ecf73f5b5aba7fbdcdf92.pdf)

**Comment by fengmk2** [comment]
抽奖程序代码在: http://bi.tmall.com/choujiang
抽奖名单: 88人 https://gist.github.com/fengmk2/8090864

由于我们人肉计数错误, 多抽了1一个, 所有中奖者有11人, 他们是:

@xudafeng 
@akecn 
@fakefish 
@Birdbird 
@robustfengbin 
@weakish 
@q3058098 
@Ysudo 
@leoner 
@qiushilee 
@mailzwj 

请以上@ 到的同学, 将收货地址, 姓名, 联系电话等基本信息, email到 fengmk2@gmail.com , 标题: nodeparty 领取奖品. 以便我们尽快快递出去.

抽奖过程视频在此：http://v.youku.com/v_show/id_XNjUxODY2NzI0.html

**Comment by weakish** [comment]
>  将收获地址, 姓名, 联系电话等基本信息

s/获/货/

**Comment by fengmk2** [comment]
@weakish ... done

**Comment by fengmk2** [comment]
@akecn @q3058098 @Ysudo @qiushilee 这4位中奖的同学, 请看到邮件提醒给我发一下寄送地址.

**Comment by noodlesC** [comment]
没人要就给我吧！

------------------ 原始邮件 ------------------
发件人: "fengmk2";notifications@github.com;
发送时间: 2013年12月23日(星期一) 下午5:10
收件人: "cnodejs/nodeparty"nodeparty@noreply.github.com; 
抄送: "来碗烫吧,孟婆!"280841866@qq.com; 
主题: Re: [nodeparty] 12月21号，NodeParty杭州站 (#2)

@akecn @q3058098 @Ysudo @qiushilee 这4位中奖的同学, 请看到邮件提醒给我发一下寄送地址.

**Comment by unrealinux** [comment]
发给我也可以啊，这么好的东西！呵呵，求发，谢谢

------------------ Original ------------------

**Comment by runkingzhang** [comment]
没有抽到的瞬间我就去淘宝上买了一本。不像上面那两位意淫兄弟。@Jackson Tian 下次帮我签名句可以了，但是你那个签名真的是不容直视。

**Comment by myst729** [comment]
书没人要就给我吧！

**Comment by runkingzhang** [comment]
@子婴 能不能把NodeParty前 你分享的用node.js搭建的图书馆的github地址发我一下，我也想搭建一个，谢谢。

**Comment by jerryge** [comment]
再抽一下？哈哈

**Comment by fengmk2** [comment]
@q3058098 @Ysudo 请这两位同学今天下午4点前回复邮件, 过期我们将重新抽奖.

**Comment by fengmk2** [comment]
@runkingzhang 应该是这个 https://github.com/mailzwj/book

**Comment by runkingzhang** [comment]
@ fengmk2  谢谢 我看看

**Comment by mailzwj** [comment]
// 配置信息 config.js
    var mongo = require("mongoskin");
    module.exports = {
    db: '',
    port: 8000,
    dburl: "mongodb://xxxxxx:user@pwd.mongolab.com:port/books",
    switchToLocal: function () {
        this.port = 8080;
        this.dburl = ":@127.0.0.1:27017/books";
    },
    start: function (local) {
        if (local) {
            this.switchToLocal();
        }
        this.db = mongo.db(this.dburl);
    }
};
图书馆那个，有个大致如上的配置文件，由于存在数据库信息，当时没放到仓库中去...

**Comment by Wuvnen** [comment]
不好意思，受某次抢票插件issue邮件轰炸影响。关闭了邮件提醒。刚刚看到。邮件已发。

**Comment by fengmk2** [comment]
当年参加了 nodeparty 的各位，到现在还在坚持下来继续做 Node.js 相关研发工作的吗？如果有，可以联系我哦，我们招聘当年有梦想的你 https://cnodejs.org/topic/59fe84cbe8350bfb218568c2 。
