### ISSUE TITLE
求今天NodeParty玉伯的PPT或者谁能告诉我下国内哪些公司采用了前端Node负责后端UI层的方式？

### ISSUE THREAD

**Issue by gudh** [cnodejs/nodeparty#5]
求今天NodeParty玉伯的PPT或者谁能告诉我下国内哪些公司采用了前端Node负责后端UI层的方式？

上次看过Nicholas的[Node.js and the new web front-end](http://www.nczonline.net/blog/2013/10/07/node-js-and-the-new-web-front-end/)，非常认同，今天@lifesinger也讲了，所以想问下哪些公司已经在用这种方式了？

先谢了

**Comment by fengmk2** [comment]
已经提交了, 请查看 https://github.com/cnodejs/nodeparty/issues/2

**Comment by gudh** [comment]
@fengmk2 多谢
