### ISSUE TITLE
下一站在那里?

### ISSUE THREAD

**Issue by fengmk2** [cnodejs/nodeparty#6]
成都? 西安? 还是厦门?

请有能力帮忙的同学, 回复本帖.

**Comment by hsqlu** [comment]
厦门吧

**Comment by guuuuo** [comment]
厦门！来吧！

**Comment by alsotang** [comment]
“下一站是不是天堂，就算失望也不能绝望。” -- 五月天《倔强》

这站蘑菇街，下一站，天！堂！软！件！园！

（....忽略我）

**Comment by alsotang** [comment]
@hayeah 你这边有什么新活动的计划吗？有的话大家可以合作啊
