### ISSUE TITLE
杭州2014年11月01日 NodeParty

### ISSUE THREAD

**Issue by JacksonTian** [cnodejs/nodeparty#7]
### 时间

2014-11-01, 星期六, 小光棍节, 下午 14:00 开始
### 规模

50-60人
#### 分享（下午）
- @dead-horse 《koa-kick-off》 https://github.com/koajs/koa/issues/355 将带来koa方面的分享
- @LeezQ 《模板通用方案》
- @fishbar 《Cube - 浏览器端代码 node 化方案》
- @jiyinyiyong 《React.js 介绍》。会现场教大家做一个 Todolist
- @fantasyni 《Write simple, maintainable NodeJs》 分享通过bearcat提供的IoC, AOP, 一致性配置来编写简单，可维护的企业级多人维护Node项目
- 5分钟闪电分享 （5个）
  - @xudafeng [《小而美的slides工具》](https://github.com/xudafeng/startserver)
#### 编码活动（傍晚）:
- @alsotang 《Node.js 初体验》 与 Node.js 的初学者一起写几行入门代码。请想要参与的同学带上装有 *nix 系统的笔记本电脑。参考 https://github.com/alsotang/node-lessons
  
  有 Javascript 基础但是完全没有玩过 Node.js 的，我们会提供 learnyounode 入门教程
### 奖品

待定
- 深入浅出[繁体](http://weibo.com/1640328892/BqX7Mxbh3)签名纪念版
- 赞助商赞助的图书
#### 赞助商

－ 图灵教育
[![turing](https://cloud.githubusercontent.com/assets/327019/4729855/ebf07058-598e-11e4-94b8-85c8febf428e.png)](http://www.ituring.com.cn/)
－ 华章图书
[![huazhang](https://cloud.githubusercontent.com/assets/327019/4729879/367f32ee-598f-11e4-8d34-b234fbd096ca.png)](http://www.hzbook.com/ps/)
### 堂食
- 免费可乐
### 报名规则

在本issue里留 +1
### 地点

[蘑菇街](http://www.mogujie.com/us/): [浙江省杭州市西湖区古墩路99号浙商财富中心一号楼](http://j.map.baidu.com/eStex)
[![image](https://cloud.githubusercontent.com/assets/156269/4705331/93a9ba2c-587a-11e4-877a-d555b14514bd.png)](http://j.map.baidu.com/eStex)

**Comment by LeezQ** [comment]
顶。欢迎来我街！到时候会提供各种饮料和零食 ：） 
另外自己开车来的同学，到时候会提供停车票，可以抵扣停车费。

**Comment by xiaoqiang730730** [comment]
赞

**Comment by fengmk2** [comment]
:100:

**Comment by shangjiyu** [comment]
顶

**Comment by haoqunjiang** [comment]
+1

**Comment by fakefish** [comment]
+1

**Comment by dingo826** [comment]
加1

**Comment by kele86838437** [comment]
+1

**Comment by ericdum** [comment]
+1

**Comment by liyao** [comment]
棒棒的！+1，欢迎来街上~~

**Comment by portwatcher** [comment]
+1

**Comment by CYCOK** [comment]
+1学生党 可以吗 有什么限制没

**Comment by dead-horse** [comment]
家门口啊，不过10-18 好像在上海...

**Comment by teamrun** [comment]
+1

**Comment by wxygeek** [comment]
哎妈呀 +1

**Comment by FelixLv** [comment]
+1

**Comment by LeezQ** [comment]
@CYCOK 没有限制 ：）

**Comment by LeezQ** [comment]
@dead-horse 听说你要参加 qcon 啊，而且还是在我们boss后面演讲，:+1:

**Comment by edagarli** [comment]
+1

**Comment by Harbon** [comment]
+1

**Comment by taojie0307** [comment]
+1

**Comment by Va-doubles** [comment]
+1

**Comment by FeeiCN** [comment]
+1

**Comment by zscorpio** [comment]
+1

**Comment by xiaozi** [comment]
+1

**Comment by wuwb** [comment]
+1 
cool!

**Comment by dead-horse** [comment]
今年可以搞个不一样形式的么？不搞演讲，玩玩 workshop 什么的.. @JacksonTian @fengmk2

**Comment by xiongsongsong** [comment]
+1

**Comment by zjnusoft** [comment]
+1

**Comment by yorkie** [comment]
+1 workshop +1 第一次参加

**Comment by Twwy** [comment]
+1

**Comment by irwenqiang** [comment]
贵街V5 报名.

**Comment by dntzhang** [comment]
++1- -

**Comment by jixiangac** [comment]
++++1

**Comment by elrrrrrrr** [comment]
回乡探亲 下次有机会再参加 : )

**Comment by qinnnnnnnn** [comment]
+1

**Comment by px-Jagten** [comment]
+1

**Comment by kennyluck** [comment]
+1

**Comment by Mr1024** [comment]
赞，距离杭州有点远

**Comment by krisjin** [comment]
赞

**Comment by FEsy** [comment]
++1

**Comment by alankell** [comment]
+1

**Comment by acmoon** [comment]
+1

**Comment by NanOrUndefind** [comment]
+1

**Comment by imsobear** [comment]
+1

**Comment by FarmanYu** [comment]
+1

**Comment by 393799203** [comment]
+1

**Comment by cherry728** [comment]
+1

**Comment by michaeljunlove** [comment]
+1

**Comment by songbingyu** [comment]
+1

**Comment by dead-horse** [comment]
莫名其妙怎么变嘉宾了..

**Comment by JacksonTian** [comment]
你以为跑得掉？

**Comment by zhangyuheng** [comment]
+1
家门口

**Comment by 4tj** [comment]
+1

**Comment by sskyy** [comment]
+1

**Comment by FFish** [comment]
+1

**Comment by useaname** [comment]
+1

**Comment by ikobe-zz** [comment]
+1

**Comment by Bonkebo** [comment]
+1

**Comment by fengmk2** [comment]
20號D2, 然後11.1, @JacksonTian 你的寶寶不是這幾天出生麼?

**Comment by xuyuan923** [comment]
+1 期待已久~~~！

**Comment by JaydenGui** [comment]
+1

**Comment by lwbjing** [comment]
+1 看看能不能搭上末班车。。。

**Comment by JacksonTian** [comment]
@fengmk2 20号左右。NodeParty我负责帮你们准备，不负责参加。到时候你来主持好了。

**Comment by grahamle** [comment]
+1  .timeline-comment-wrapper 已经有67个了。看来没赶上末班车

**Comment by fengmk2** [comment]
看來獎品有可能是樸靈老師深淺繁體簽名版了
2014-10-10 下午10:09于 "Jackson Tian" notifications@github.com写道：

**Comment by marshalYuan** [comment]
+1

**Comment by useaname** [comment]
+1

**Comment by wangxingyun** [comment]
＋1

**Comment by yukihosoul** [comment]
+1

**Comment by xiaoqiang730730** [comment]
+1

**Comment by ViccRondo** [comment]
+1

**Comment by plantvsbirds** [comment]
:+1: +1

**Comment by qinnnnnnnn** [comment]
@fengmk2 还以为奖品会是樸靈老師的寶寶~ :+1:

**Comment by cococa** [comment]
1  （有啥要求没？）

**Comment by willkan** [comment]
+1

**Comment by rigao** [comment]
+1

**Comment by Phinome** [comment]
+1

**Comment by shihongzhi** [comment]
+1

**Comment by fishbar** [comment]
+10086

**Comment by XadillaX** [comment]
+10087

**Comment by adoyle-h** [comment]
+1

**Comment by Amunu** [comment]
+1

**Comment by byteshijinn** [comment]
刚发现这个。。。看来还是工作太忙看微博时间少了

**Comment by luckyddx** [comment]
+1

**Comment by byteshijinn** [comment]
+1

**Comment by lisposter** [comment]
+1

**Comment by biangbiang** [comment]
+1

**Comment by kaidiren** [comment]
+1

**Comment by xudafeng** [comment]
+1

**Comment by fengmk2** [comment]
征集 5 分钟快速分享，可以分享自己得意的模块或者工具。
要求：
1. 限时5分钟
2. 要有 slides 展示
3. 拒绝广告

@xudafeng 你是否可以报名一个？

**Comment by xudafeng** [comment]
@fengmk2 , 报一个《小而美的slides工具》

**Comment by dead-horse** [comment]
@xudafeng 发给我试用一下，哈哈

**Comment by XadillaX** [comment]
什么主题色提取 thmclrx，什么 ORM 什么的都可以吗 0. 0

**Comment by xudafeng** [comment]
@dead-horse [click](https://github.com/xudafeng/startserver)

**Comment by fengmk2** [comment]
@xudafeng 赞！

欢迎其他同学报名5分钟闪电分享!

**Comment by fengmk2** [comment]
@XadillaX 都可以

**Comment by fengmk2** [comment]
跟@LeezQ 聊完，蘑菇街场地能支持到晚上，哈哈，打算在分享之后直接办起 [nodeschool](http://nodeschool.io/)，如果大家想参与 nodeschool 的，请带上你的笔记本电脑。

技能要求：
- 会基本的 Javascript

将进行一下两门课程：
- learnyounode: Learn You The Node.js For Much Win! An intro to Node.js via a set of self-guided workshops.
- kick-off-koa: Getting start with Koa, the next generation web framework for Node.js.

@alsotang 负责去申请一下 http://nodeschool.io/host.html

**Comment by alsotang** [comment]
+1

@fengmk2 ok，我看看

**Comment by alsotang** [comment]
我觉得我这课程就不错啊：https://github.com/alsotang/node-lessons
nodeschool 可是英文的..要考虑大众的接受水平啊..

**Comment by fengmk2** [comment]
good，那我们改用符合国情的教程

**Comment by alsotang** [comment]
这就太棒了！专注 Node，绕过语言障碍。

**Comment by alsotang** [comment]
@fengmk2 我觉得编码活动可以分两拨来玩。

一拨是初学者们一起玩 node-lessons，一拨是大神们一起 hackathon（主要我喜欢看 @dead-horse 敲键盘，它敲键盘的速度完全受限于硬件的速度）。

hackathon 的内容要不大家一起想想？

**Comment by XadillaX** [comment]
@alsotang，据说 @lisposter 加了 nodeschool 站点的 i18n 的中国支持。

**Comment by alsotang** [comment]
@XadillaX 确实有简体中文的支持，我问问他有没有兴趣一起组织一下。

**Comment by alsotang** [comment]
@luin 还搞 node 吗最近？nodeparty 一起来搞搞啊

**Comment by luin** [comment]
@alsotang 搞呀，我在的组就弄 node 的，没问题~

**Comment by hayeah** [comment]
可惜我不在了。。。残念

**Comment by alsotang** [comment]
@hayeah 你在就好办了，上次成都组织得那么好。

**Comment by mapleincode** [comment]
+1  不知道还有木有位置~

**Comment by lisposter** [comment]
@XadillaX @alsotang  其实加简体中文就是一时兴起的事~也没啥技术含量的，要是有用得上我的地方，尽管说~ :ok_hand:

**Comment by hayeah** [comment]
@loddit 你一号可以来打打酱油

**Comment by loddit** [comment]
大家好  我正好经过杭州来看看哈~ +1

**Comment by loddit** [comment]
如果大家对 Meteor 感兴趣我可以介绍一下哈

**Comment by nihgwu** [comment]
+1 貌似来晚了。。。

**Comment by fishbar** [comment]
@JacksonTian  +我的主题： Cube - 浏览器端代码node化

**Comment by thondery** [comment]
+1

**Comment by thondery** [comment]
不知道有没有位置了~

**Comment by fengmk2** [comment]
@alsotang 不搞 hackathon 了，还是以 workshop 为主，希望在几个小时里，让更多人能装上 Node.js ，写上几行能运行的代码，解决几个实际遇到的问题。

**Comment by fengmk2** [comment]
[蘑菇街](http://www.mogujie.com/us/) 所在的地址: 浙江省杭州市西湖区古墩路99号浙商财富中心一号楼

**Comment by stormlei** [comment]
+1

**Comment by px-Jagten** [comment]
+1

**Comment by jzlxiaohei** [comment]
+1

**Comment by teabyii** [comment]
+1

**Comment by eeandrew** [comment]
+1 我来晚了

**Comment by alsotang** [comment]
@loddit meteor 的这个中文文档：http://d0cs.meteor.com/ 可以交给你维护啊：）

**Comment by hc2014** [comment]
+1  不知道还有没有位置

**Comment by Neil-UWA** [comment]
+1

**Comment by hc2014** [comment]
+1

 ------------------ 原始邮件 ------------------
  发件人: "Neil";notifications@github.com;
 发送时间: 2014年10月21日(星期二) 下午2:19
 收件人: "cnodejs/nodeparty"nodeparty@noreply.github.com; 
 抄送: ""294836881@qq.com; 
 主题: Re: [nodeparty] 杭州2014年11月01日 NodeParty (#7)

+1

**Comment by kidbai** [comment]
+1

**Comment by fengliner** [comment]
顶，可惜去不了

**Comment by omnip620** [comment]
+1

**Comment by qiuyuntao** [comment]
+1

**Comment by crmok** [comment]
+1

**Comment by JiaxiangZheng** [comment]
+1

**Comment by tong-zeng** [comment]
+1

**Comment by Sunnyson303** [comment]
+1

**Comment by shelbeniskb** [comment]
+1

**Comment by Sunnyson303** [comment]
+1

------------------ 原始邮件 ------------------
发件人: "shelbeniskb"notifications@github.com; 
发送时间: 2014年10月22日(星期三) 上午9:30
收件人: "cnodejs/nodeparty"nodeparty@noreply.github.com; 
抄送: "橘子涩"260851801@qq.com; 
主题: Re: [nodeparty] 杭州2014年11月01日 NodeParty (#7)

+1

**Comment by glh1991** [comment]
+1

**Comment by Sunnyson303** [comment]
+1

------------------ 原始邮件 ------------------
发件人: "allen";notifications@github.com;
发送时间: 2014年10月22日(星期三) 上午9:46
收件人: "cnodejs/nodeparty"nodeparty@noreply.github.com; 
抄送: "橘子涩"260851801@qq.com; 
主题: Re: [nodeparty] 杭州2014年11月01日 NodeParty (#7)

+1

**Comment by minnoooo** [comment]
+1

**Comment by kennyluck** [comment]
+1

**Comment by zhangzifa** [comment]
+1

**Comment by august-zou** [comment]
+1

**Comment by iamnotblank** [comment]
+2014

**Comment by albertshaw** [comment]
+1

**Comment by minsa** [comment]
+1

**Comment by SummerFans** [comment]
千呼万唤来+1

**Comment by captainblue2013** [comment]
如无意外可以来

**Comment by captainblue2013** [comment]
+1

**Comment by jinphen** [comment]
+1  就在我住的边上

**Comment by JonZLX** [comment]
+1

**Comment by dramogu** [comment]
+1

**Comment by sprying** [comment]
+1

**Comment by PerterPon** [comment]
地点在蘑菇街？

**Comment by ironM** [comment]
+1

**Comment by imhu** [comment]
+1

**Comment by ManShow0122** [comment]
+1 现在还有位子吗？

**Comment by Suixinlei** [comment]
+1 同想问还有位子吗

**Comment by xhuiinit** [comment]
+1 还有位子么，距离很近

**Comment by ateoa** [comment]
＋1 一看地址 就在边上

**Comment by lcoder** [comment]
+12

**Comment by morrain** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by makaiqian** [comment]
+1

**Comment by bluetomlee** [comment]
+1 貌似没位置了啊

**Comment by bear-qv** [comment]
+1 好像没位置了诶。

**Comment by alsotang** [comment]
楼上的各位，通知一下：
1. 来的时候如果想参加接下来的 Node.js 体验活动，请带上笔记本电脑。我们会开展一些面向初学者的教学活动。会场有 wifi。
2. 相关的 party 信息已经确定，请大家看一下更新后的 issue

**Comment by alsotang** [comment]
@dead-horse @LeezQ @fishbar @jiyinyiyong 麻烦嘉宾们确定一下自己的分享标题，以及简要描述一下分享概述。

**Comment by alsotang** [comment]
@xudafeng 麻烦提供一下概述。

**Comment by bear-qv** [comment]
@alsotang   担心人数问题，因为要和学校请假。求答复人数满了吗？

**Comment by tiye** [comment]
+1 给大家做一个关于 React.js 简短的分享, "React.js 介绍(Todolist 做例子)"

**Comment by fengmk2** [comment]
@FySuper 人数没问题的，场地能容纳100人

**Comment by fantasyni** [comment]
还可以加个分享吗？大概分享40分钟左右 上次hangjs没报上名的  

```
Write simple, maintainable Nodejs
```

**Comment by alsotang** [comment]
@fantasyni 邮件跟我说说标题，概述，以及你的大概信息。谢谢。alsotang@gmail.com

**Comment by EthanCodeCraft** [comment]
+1 好活动

**Comment by fantasyni** [comment]
@alsotang 已发你哈。。。

**Comment by xiaoye1988** [comment]
+1 还有名额么？

**Comment by runkingzhang** [comment]
+1

**Comment by qd1993102** [comment]
+1

**Comment by xwartz** [comment]
+1就在边上

**Comment by iversong** [comment]
+1

**Comment by lunbawu** [comment]
+1   看起来有好多人参加，我也参加看看。。刚好想学NODE.JS

**Comment by Colin6618** [comment]
+1

**Comment by Tankpt** [comment]
+1

**Comment by mackjoner** [comment]
表示支持了

**Comment by zenghongyujia123** [comment]
+1

**Comment by zzee203** [comment]
+1

**Comment by mavericksw** [comment]
+1

**Comment by grasp** [comment]
+1

**Comment by zaraguo** [comment]
+1

**Comment by stylehuan** [comment]
+1，顶

**Comment by rubyisapm** [comment]
+1

**Comment by chujinghui** [comment]
+1

**Comment by zywj** [comment]
+1

**Comment by lixiaocheng18** [comment]
+1

**Comment by fanghm** [comment]
+1

**Comment by xiaoman123** [comment]
+1

**Comment by wxlfight** [comment]
+1

**Comment by sabakugaara** [comment]
+1

**Comment by cybercoding** [comment]
+1

**Comment by kalxd** [comment]
+1

**Comment by think2011** [comment]
-1 一定要记得高清视频呀~~

**Comment by my19940202** [comment]
有点想去，一看居然有这么多人，顿时胆怯了

**Comment by my19940202** [comment]
+1

**Comment by shadowdaw** [comment]
今天刚开始学。可以来吗!!

**Comment by shadowdaw** [comment]
+1

**Comment by futurelord** [comment]
+1

**Comment by gjf281** [comment]
+1

**Comment by tiankongkong224** [comment]
+1

**Comment by JacksonTian** [comment]
这次评论有200+。除了讨论外，估计有150人报名。有史以来报名最多的一次。以下Actions请大家注意：
- @alsotang 准备签名表。
- 楼上报名的同学们，明天请凭github id签到。
- 本次奖品丰厚，主题丰富，enjoy it.
- 要参加晚上的lesson的，请自己带好电脑和先安装好环境。
- 请于1:30到达。2:00正式开始。

以上就是本次活动的通知，地点，路线请看本帖主题内容。

**Comment by fengmk2** [comment]
朴老师复出了，期待！

**Comment by XadillaX** [comment]
@JacksonTian *lesson，笔误 2333333

**Comment by shanliang** [comment]
+1

**Comment by luoluosa** [comment]
+1

**Comment by wrbing728** [comment]
+1

**Comment by FEsy** [comment]
+1,最后能否把ppt补发一下啊

**Comment by SummerFans** [comment]
非常的激动啊~~

**Comment by py8765** [comment]
+1

**Comment by teamrun** [comment]
sorry... 明天公司上线东西, 全体加班....  我 还有同事@FelixLv @jzlxiaohei @px-Jagten 都去不了了... 遗憾啊...

**Comment by JacksonTian** [comment]
收到。

**Comment by Suixinlei** [comment]
很遗憾啊这-------- 原始邮件 --------主题：Re: [nodeparty] 杭州2014年11月01日 NodeParty (#7)发件人：teamrun 收件人：cnodejs/nodeparty 抄送：隋鑫磊 sorry... 明天公司上线东西, 全体加班....  我 还有同事@FelixLv @jzlxiaohei @px-Jagten 都去不了了... 遗憾啊...

—Reply to this email directly or view it on GitHub.
{"@context":"http://schema.org","@type":"EmailMessage","description":"View this Issue on GitHub","action":{"@type":"ViewAction","url":"https://github.com/cnodejs/nodeparty/issues/7#issuecomment-61255289","name":"View Issue"}}

**Comment by xhuiinit** [comment]
非常抱歉，项目工期催紧，项目组全体加班。到不了了，无奈！

**Comment by loddit** [comment]
啊 四点才到杭州，只能赶过去看后半场了

**Comment by yurenane** [comment]
+1

**Comment by albertshaw** [comment]
好遗憾，要加班，晚场几点到几点，还是想看看能不能去

**Comment by Suixinlei** [comment]
有没有杭电的求同行

**Comment by chenxianliang** [comment]
+1

**Comment by frankeen** [comment]
+1

**Comment by ahbing** [comment]
+1

**Comment by alsotang** [comment]
说到杭州的活动，七牛有个《开发者最佳实践日》系列活动 11 月 15 日会在杭州举办，这一期的主题是开发者工具，详情可见：http://qiniu-5.eventdove.com/

![image](https://cloud.githubusercontent.com/assets/1147375/4871176/6b0d900e-61a1-11e4-8a32-dc03a4a8b72c.png)

微信扫这个码加群的话，到时在现场会赠送“男性专用神密小礼物”（引号中是引用的）。
