### ISSUE TITLE
广州2014年12月06日 NodeParty UC场

### ISSUE THREAD

**Issue by JacksonTian** [cnodejs/nodeparty#8]
## 分享纪录和PPT

http://segmentfault.com/blog/binarytree/1190000002410458
## 简介
- NodeParty是 [CNode社区](https://cnodejs.org/) 的线下交流活动品牌。不定期在全国一线城市举办。目前举办过NodeParty的城市有北京、上海、杭州、深圳、香港。
- 主要分享内容为node.js开发及javascript周边技术。
## 时间

2014-12-06, 星期六 下午13:30开始
## 规模

100 ~ 200 人
## 地点

UC优视 (广州市天河区黄埔大道西平云路163号广电平云广场B塔15楼)
[参见百度地图 http://j.map.baidu.com/btU8y ](http://j.map.baidu.com/btU8y)

**交通指引**

> 1.公交线路：
> 137、140、194、218、243、245、261、278、284、43、53、504、506、510、517、518、540、541、542、548、550、583、701、704、807、828、840、841A、842A、B8、B15、大学城4线到华侨医院（潭村）站，步行8-10分钟到达广电平云广场。
> 
> 2.地铁线路：
> 地铁5号线潭村站C出口，步行10-15分钟到达广电平云广场。
> 
> 3.其它未尽提醒或指引事宜，如需帮助，请联系微博帐号：http://weibo.com/liuyong25 。

![image](https://cloud.githubusercontent.com/assets/227713/5259079/e3401216-7a35-11e4-87ef-9ebb30951669.png)
## 活动安排

| 时间 | Topic | 讲师 |
| --- | --- | --- |
| 13:30-13:50 | 签到、发礼物、发抽奖劵 | 数量有限，先到先得 |
| 14:00-14:40 | 「[koa：不仅仅是 generator](http://deadhorse.me/slides/koa-not-only-generator.pdf)」 | @dead-horse ([koa  maintainer](https://github.com/koajs/koa)) |
| 14:40-15:20 | 「[基于Node.js的数据统计系统实践](https://github.com/chemdemo/mstats-nodeparty/blob/master/slider/mstats-nodeparty.pdf)」 | @chemdemo (唯品会移动事业部) |
| 15:20-15:50 | 茶歇、交流 | - |
| 15:50-16:00 | 「[基于nodejs的移动端调试工具](http://slides.com/zack-lin/mobile-debugger#/)」 | @zack-lin  (UC大导航组) |
| 16:00-16:40 | 「[MinDB - Database on JavaScript](http://iwillwen.u.qiniudn.com/slides/MinDB.pdf)」 | @iwillwen (跨界工程师，[MinDB作者](https://github.com/iwillwen/mindb)) |
| 16:40-17:20 | 「[模板引擎，我们比的是情怀](http://pan.baidu.com/s/1mgmjuR2)」 | @leizongmin ([「Node.js 实战」作者之一](http://www.amazon.cn/%E5%9B%BE%E4%B9%A6/dp/B00JPVNIFY)) |
| 17:20-18:00 | 抽奖、交流、合影 | - |

---
### 1.UC提供的神秘大奖

![uc-gift](https://cloud.githubusercontent.com/assets/227713/5176961/38ee022c-748c-11e4-8667-5da1a14058d6.jpg)
### 2.萌萌哒的SegmentFault杯子

![2014-09-18 16 50 45](https://cloud.githubusercontent.com/assets/327019/5102103/dce6ad5c-6fff-11e4-8974-a3cb5542adb6.jpg)
### 4.图灵提供的书籍若干

---
## 赞助商
- [![uc-logo](https://cloud.githubusercontent.com/assets/227713/5163484/0c8e86f0-7407-11e4-8821-40ade8732504.png)](http://www.uc.cn/)
- [![sf-logo-cmyk](https://cloud.githubusercontent.com/assets/327019/5102025/a781a8d4-6ffe-11e4-9d1c-373d7fe23d08.png)](http://segmentfault.com/)
- [![broadview-logo1](https://cloud.githubusercontent.com/assets/227713/5163330/3c3f7960-7405-11e4-965d-70ba6ced893e.png)](http://www.broadview.com.cn/)
- [![broadview-logo2](https://cloud.githubusercontent.com/assets/227713/5163331/43b81940-7405-11e4-8902-11d029474d55.png)](http://www.broadview.com.cn/)
## 零食
- 传说中的UC食堂特供
- ![uc-food](https://cloud.githubusercontent.com/assets/227713/5176997/e17c7f36-748c-11e4-99a6-7574dd04d374.png)
## 报名规则

老规矩，在本issue里留 +1

**Comment by ChJJin** [comment]
+1 !!!!! (竟然是沙发)

**Comment by honwhy** [comment]
+1 ！！！！

**Comment by yneear** [comment]
+1 (

**Comment by xingrz** [comment]
+1 去去去去去去去去！

**Comment by johndeng** [comment]
+1

**Comment by jianhaozh** [comment]
+1

**Comment by TomHuangCN** [comment]
+1

**Comment by huqihang** [comment]
+1

**Comment by fanchou** [comment]
+1

**Comment by jincdream** [comment]
报名~~！！！！！！+1

**Comment by zzbo** [comment]
+1

**Comment by annilq** [comment]
+1

**Comment by zaykl** [comment]
+1

**Comment by Manho** [comment]
+1

**Comment by neoblackcap** [comment]
+1

**Comment by AnnZ** [comment]
+1

**Comment by t2krew** [comment]
+1

**Comment by sundyxfan** [comment]
+1

**Comment by hello123leo** [comment]
+1

**Comment by ShaopengHe** [comment]
+1

**Comment by lakb248** [comment]
+1

**Comment by p2227** [comment]
+1

**Comment by villins** [comment]
＋1

**Comment by thondery** [comment]
＋1

**Comment by edwinaclau** [comment]
＋1

**Comment by lys623** [comment]
＋1

**Comment by rigao** [comment]
+1

**Comment by shucheng** [comment]
+1

**Comment by gaojuzhang** [comment]
+1

**Comment by LuoPQ** [comment]
+1

**Comment by jinges** [comment]
+1

**Comment by jiehe** [comment]
+1

**Comment by caizeng** [comment]
这么低调的报名方式···

**Comment by Cassiejj** [comment]
+1

**Comment by RemielOrz** [comment]
+1

**Comment by zack-lin** [comment]
+1

**Comment by JerroldLee** [comment]
怎么没收到风呢？

**Comment by zdan** [comment]
+1

**Comment by southnan0** [comment]
+1

**Comment by fwon** [comment]
+1

**Comment by chileung** [comment]
+1

**Comment by csbun** [comment]
+1

**Comment by gdcnb** [comment]
+!

**Comment by wurh** [comment]
+1

**Comment by xiaokaike** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by cookjs** [comment]
+1

**Comment by wteam-xq** [comment]
+1， 离开始时间还有好久诶。

**Comment by zwlcoding** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by TLang622** [comment]
+1

**Comment by srisy** [comment]
+1

**Comment by fangsini** [comment]
+1

**Comment by kinglion** [comment]
+1

**Comment by leadwit** [comment]
+1

**Comment by birdxiao** [comment]
+1

**Comment by fouber** [comment]
+1

**Comment by Megantao** [comment]
+1

**Comment by fangbiao** [comment]
+1

**Comment by shellphon** [comment]
+1

**Comment by shihuihzh** [comment]
+1

**Comment by huaconghub** [comment]
+1

**Comment by djyde** [comment]
+1

**Comment by lisaRao** [comment]
支持~~

**Comment by panelwe** [comment]
+1

**Comment by TreeLin** [comment]
+1

**Comment by suinia** [comment]
+1

**Comment by xiao-T** [comment]
+1

**Comment by pasicopan** [comment]
+1

**Comment by YoRolling** [comment]
+1

**Comment by 514366607** [comment]
+1

**Comment by Hiufan** [comment]
+1

**Comment by Tronsfey** [comment]
+1

**Comment by hokein** [comment]
+1

**Comment by Running-He** [comment]
+1

**Comment by sunshineg** [comment]
我大 SegmentFault 以后会多多支持Node小伙伴技术活动哒，多多勾搭搞起来
+1
![jiedui](https://cloud.githubusercontent.com/assets/1147886/5103156/90ac824e-700f-11e4-9a8e-c0ab6e32011f.jpg)

**Comment by WongYuenYuen** [comment]
+1

**Comment by bramblex** [comment]
＋1

**Comment by hoohack** [comment]
+1

**Comment by Galen-Yip** [comment]
+1

**Comment by wuxianrun** [comment]
+1

**Comment by chemdemo** [comment]
+1

**Comment by chemdemo** [comment]
终于有广州Node场了，讲师怎么报名呢？

**Comment by booxood** [comment]
+1

**Comment by mexiQQ** [comment]
＋1

**Comment by badoths** [comment]
+1

**Comment by YaomiHuang** [comment]
+1

**Comment by walkdoer** [comment]
+1

**Comment by landerqi** [comment]
+1

**Comment by rongtou** [comment]
+1

**Comment by qq826592522** [comment]
+1

**Comment by daddybh** [comment]
+1

**Comment by xpingzo** [comment]
+1

**Comment by cc258** [comment]
+1:underage:

:crown::crown::crown::crown::crown:

**Comment by jimmyxie** [comment]
+1

**Comment by swan163** [comment]
+1

**Comment by wentatte** [comment]
+1

**Comment by su9er** [comment]
+1，终于来广州啦，必须去啊

**Comment by Terry-lzs** [comment]
+1

**Comment by hippasus** [comment]
+1

**Comment by h3l** [comment]
+1

**Comment by codelint** [comment]
+1

**Comment by warm1204** [comment]
+1

**Comment by kenspirit** [comment]
+1

**Comment by wenhebrews** [comment]
+1

**Comment by Newcandy** [comment]
+1

**Comment by benhero** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by liuyidi** [comment]
+1

**Comment by yygy125** [comment]
+1

**Comment by fuemoshi** [comment]
+1

**Comment by kiroChen** [comment]
+1

**Comment by cyhunter** [comment]
+1

**Comment by tranch** [comment]
+1

**Comment by 4074** [comment]
+1

**Comment by spacewander** [comment]
+1

**Comment by spacewander** [comment]
来得太晚了……有考虑加人数么？

**Comment by koon-kai** [comment]
+1

**Comment by freemanlingli** [comment]
+1

**Comment by Edward1992** [comment]
+1

**Comment by sysatom** [comment]
+1

**Comment by yukjin** [comment]
+1

**Comment by yukjin** [comment]
朴灵会到场吗

**Comment by quanix** [comment]
+1

**Comment by majintao** [comment]
+1

**Comment by WongYuenYuen** [comment]
+1

2014-11-20 23:08 GMT+08:00 jmark notifications@github.com:

**Comment by billfeller** [comment]
+1

**Comment by iwillwen** [comment]
@dead-horse 啊哈，本来想讲Generator的，没想到死马过来讲了。

---

Will Wen Gunn - Senior JavaScript Engineer, Web Architect

**Comment by itrunc** [comment]
+1

**Comment by fengmk2** [comment]
哈哈，正好那周出差广州，去提问题拿杯子

**Comment by atian25** [comment]
@fengmk2  4号的行程？ good~

**Comment by donson** [comment]
+1

**Comment by Ravior** [comment]
+1

**Comment by think2011** [comment]
+1

**Comment by zack-lin** [comment]
@JacksonTian 林子杰 github is @zack-lin

**Comment by VectorHo** [comment]
+1

**Comment by zqWu** [comment]
+1

**Comment by neekychan** [comment]
+1

**Comment by RansonT** [comment]
+1

**Comment by yangq1990** [comment]
+1

**Comment by 381003521** [comment]
+1

**Comment by gse7en2012** [comment]
+1

**Comment by stableShip** [comment]
+1

**Comment by p2227** [comment]
提前了一周啊 - - ||

**Comment by youyudehexie** [comment]
+1

**Comment by leizongmin** [comment]
想分享一下我的模板引擎的一些应用实例，怎么报名呢

**Comment by Aquietzero** [comment]
+1

**Comment by ggd543** [comment]
+1

**Comment by zeiny** [comment]
+1

**Comment by narellazhang** [comment]
+1

**Comment by PhoneLi** [comment]
＋1

**Comment by liulangxiong** [comment]
+1

**Comment by chemdemo** [comment]
@leizongmin 老雷啊 找下 @atian25 吧

**Comment by atian25** [comment]
@chemdemo  昨天已经沟通过了， 并更新到issue了。

**Comment by luzhanbo** [comment]
+1

**Comment by comeontom** [comment]
＋1

**Comment by luohanwen** [comment]
+1

**Comment by calent** [comment]
+1

**Comment by wwb568109135** [comment]
+1  

o(∩_∩)o

**Comment by liujiaqiid** [comment]
+1

**Comment by seasonhuang** [comment]
+1

**Comment by kekobin** [comment]
+1

**Comment by cssgdhd** [comment]
+1

**Comment by tofrookie** [comment]
+1

**Comment by kekobin** [comment]
+1

**Comment by lcg635** [comment]
+1

**Comment by zhechang520** [comment]
+1

**Comment by duziaqin** [comment]
+1

**Comment by RansonT** [comment]
+1

**Comment by narol1024** [comment]
+1

**Comment by liguanrui** [comment]
+1

**Comment by atian25** [comment]
更新议程， 更新奖品。

**Comment by iweisi** [comment]
+1

**Comment by judasn** [comment]
+1

**Comment by iwillwen** [comment]
留个名来抽奖

**Comment by dead-horse** [comment]
抽奖抽奖抽奖！

**Comment by hubcarl** [comment]
+1

**Comment by Lenchs** [comment]
+1

**Comment by Anihc** [comment]
+1

**Comment by JoshuaChen** [comment]
+1

**Comment by snowhan** [comment]
+1

**Comment by lumixlau** [comment]
+1

**Comment by transno** [comment]
+1

**Comment by yourhe** [comment]
＋1

**Comment by xuanfeng** [comment]
+1

**Comment by wujialongcn** [comment]
+1

**Comment by yourtion** [comment]
+1

**Comment by momotoo** [comment]
+1

**Comment by bossgong** [comment]
+1

**Comment by zengxianbo** [comment]
+1

**Comment by M-J2014** [comment]
+1

**Comment by SamHwang1990** [comment]
+1

**Comment by caixingorg** [comment]
+1

**Comment by plusice** [comment]
+1

**Comment by huanz** [comment]
++

**Comment by UphkcRNqmafQWcSSSSSS** [comment]
+1

**Comment by Feelin** [comment]
+1

**Comment by elaijuh** [comment]
+=1

**Comment by WongYuenYuen** [comment]
抽奖抽奖

2014-11-28 20:00 GMT+08:00 Hu Jia Le notifications@github.com:

**Comment by yesvods** [comment]
+1

**Comment by yyydao** [comment]
+1

**Comment by oooooooz** [comment]
+1

**Comment by dwqs** [comment]
+1！！！！！！！！！！！！！！！！！

**Comment by mithenji** [comment]
+1 ！~

**Comment by bobzhen** [comment]
+1

**Comment by zhongbaitu** [comment]
+1

**Comment by gdmec07120721** [comment]
+1

**Comment by Shany100** [comment]
+1 ！！！

**Comment by birdxiao** [comment]
算了下，有216人，超过100人了

**Comment by mokai** [comment]
+1 iOS开发者

**Comment by will-zhong** [comment]
+1

**Comment by shelizhou** [comment]
+1

**Comment by QLeelulu** [comment]
+1

**Comment by bailnl** [comment]
+1

**Comment by maxming2333** [comment]
+1

**Comment by ShallmentMo** [comment]
+1

**Comment by skyoo** [comment]
+1

**Comment by iwinmin** [comment]
+1

**Comment by lrrluo** [comment]
+1

**Comment by LinHeng** [comment]
+1

**Comment by replace5** [comment]
+1

**Comment by Hokinpo** [comment]
+1

**Comment by guojianlan** [comment]
+1

**Comment by bsnwong** [comment]
+1

**Comment by pascallin** [comment]
+1 !!!

**Comment by xusiyuan841028** [comment]
＋1

**Comment by digiaries** [comment]
+1

**Comment by Billzaifei** [comment]
+1

**Comment by hslleo** [comment]
+1

**Comment by sysuleiw** [comment]
+1

**Comment by jucilang** [comment]
+1

**Comment by vincezkz** [comment]
+1

**Comment by AaronPlay** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by hoolev** [comment]
+1

**Comment by zeyongTsai** [comment]
+1

**Comment by AjaxDemon** [comment]
+1

**Comment by mikuazusa** [comment]
+1

**Comment by Kenshinhu** [comment]
+1 报名

**Comment by atian25** [comment]
HI ALL， 报名已截止。

**各位切记： 签到时间为 13:30 ~ 13:50 ， 物业管理严格， 过时后会不太方便， 请准时参加。**

路线指引如下：(摘抄自邀请函)
![nope party](https://cloud.githubusercontent.com/assets/227713/5258968/3de97312-7a34-11e4-9adf-634629ee0c40.jpg)

**Comment by think2011** [comment]
@atian25  是我网络问题吗？ 我收到的邀请函的图是挂掉的。

**Comment by atian25** [comment]
@think2011 可能我被反垃圾了... 如上图, 已更新.

**Comment by think2011** [comment]
@atian25 tks! 好多人的样子，我一定会来的!

**Comment by think2011** [comment]
@atian25 tks! 好多人的样子，我一定会来的!

**Comment by think2011** [comment]
@atian25 tks! 好多人的样子，我一定会来的!

**Comment by lumixlau** [comment]
@atian25 是报了名就能去？

**Comment by atian25** [comment]
@lumixlau 嗯，我们的会议室能容纳200人，只要没挤爆了， 就可以。
但有些奖品是数量有限，先来先得的哈。

**Comment by sidecore** [comment]
+1

**Comment by lzrgibson** [comment]
+1

**Comment by fwind1** [comment]
+1

**Comment by shucheng** [comment]
@atian25  是收到邀请函才能去吗？我这边好似邮箱没有收到邀请，请问是被拒绝了吗？

**Comment by atian25** [comment]
不用担心，报名了即可参加。最好准时签到，抢个好位置。

**Comment by notalklu** [comment]
@atian25   还能报名么？+1

**Comment by shucheng** [comment]
@atian25 thx 一定准时

**Comment by dsnlfk** [comment]
+1

**Comment by atian25** [comment]
HI，攻城狮们，A U Ready？ 明天下午不见不散。

**Comment by WongYuenYuen** [comment]
抽我抽我，我是小受

2014-12-05 22:50 GMT+08:00 TZ | 天猪 notifications@github.com:

**Comment by think2011** [comment]
@atian25 激动的不想睡觉 (≧▽≦)/

**Comment by hoohack** [comment]
抽我抽我😄

**Comment by mansonchor** [comment]
+10086

**Comment by atian25** [comment]
分享纪录和PPT整理： http://segmentfault.com/blog/binarytree/1190000002410458
另外欢迎大家分享自己的一日游体会，微博话题： #NodeParty# @cnodejs

**Comment by fengmk2** [comment]
![image](https://cloud.githubusercontent.com/assets/156269/5331629/2c1ae240-7e6e-11e4-8a13-fa905f5f72a2.png)

**Comment by dead-horse** [comment]
![image](https://cloud.githubusercontent.com/assets/985607/5331882/26c3e7d2-7e79-11e4-9a31-cbec87b2052c.png)
